import { StyleSheet } from '@react-pdf/renderer';

/** Monochrome, druckerfreundlich, kompakt. A4. */
export const printColors = {
  text: '#111111',
  muted: '#555555',
  line: '#DDDDDD',
  bgSoft: '#F5F5F5',
  warn: '#000000',
};

export const sheetStyles = StyleSheet.create({
  page: {
    padding: 36,
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: printColors.text,
    lineHeight: 1.35,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottom: `1.5px solid ${printColors.text}`,
    paddingBottom: 10,
    marginBottom: 14,
  },
  brand: { fontSize: 11, fontWeight: 'bold', letterSpacing: 1 },
  brandSub: { fontSize: 8, color: printColors.muted, marginTop: 2 },
  docTitle: { fontSize: 16, fontWeight: 'bold', textAlign: 'right' },
  docMeta: { fontSize: 9, color: printColors.muted, textAlign: 'right', marginTop: 2 },
  pill: {
    alignSelf: 'flex-start',
    paddingVertical: 2,
    paddingHorizontal: 6,
    border: `1px solid ${printColors.text}`,
    fontSize: 8,
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  section: { marginBottom: 14 },
  sectionTitle: {
    fontSize: 9,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: printColors.muted,
    marginBottom: 4,
    borderBottom: `0.5px solid ${printColors.line}`,
    paddingBottom: 2,
  },
  row: { flexDirection: 'row', marginBottom: 2 },
  label: { width: 90, color: printColors.muted },
  value: { flex: 1 },
  alertBox: {
    border: `1.5px solid ${printColors.text}`,
    padding: 8,
    marginBottom: 14,
  },
  alertTitle: { fontSize: 10, fontWeight: 'bold', textTransform: 'uppercase', marginBottom: 2 },
  courseRow: {
    flexDirection: 'row',
    paddingVertical: 4,
    borderBottom: `0.5px solid ${printColors.line}`,
  },
  courseLabel: { width: 90, color: printColors.muted, fontSize: 9 },
  courseName: { flex: 1, fontWeight: 'bold' },
  courseDesc: { color: printColors.muted, fontSize: 9, marginTop: 1 },
  qtyCol: { width: 40, textAlign: 'right' },
  priceCol: { width: 70, textAlign: 'right' },
  totalRow: {
    flexDirection: 'row',
    paddingTop: 6,
    marginTop: 4,
    borderTop: `1px solid ${printColors.text}`,
  },
  totalLabel: { flex: 1, fontWeight: 'bold' },
  totalValue: { width: 90, textAlign: 'right', fontWeight: 'bold' },
  footer: {
    position: 'absolute',
    bottom: 18,
    left: 36,
    right: 36,
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 8,
    color: printColors.muted,
    borderTop: `0.5px solid ${printColors.line}`,
    paddingTop: 6,
  },
});